### PR TITLE
Adds clarification about the `document` type

### PR DESCRIPTION
**Pull request by popematt**
*Issue #, if available:*

#31

*Description of changes:*

This is probably not a complete solution for #31, but it does provides a little more detail by relating `document` back to the Ion specification.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by popematt** [comment]
I have a few more thoughts about why it's okay for us to say that a `document` must be a _finite_ value stream.

* We can never prove that an unbounded value stream is valid because there is always (in theory) more values that could arrive.
* I don't think there's a legitimate use case for unbounded streams in ISL. If you are processing an unbounded stream, you cannot wait until the entire stream is validated before moving on the the next step (transformation, storage, etc.). Therefore you must break a stream into finite chunks or use a finite sliding window over the stream to validate it in parts before passing those parts along to the next step in your process.
* In the unlikely event that we ever have a use case for validating an unbounded value stream, we can introduce a new core type for that.

**Comment by zslayton** [comment]
> In the unlikely event that we ever have a use case for validating an unbounded value stream, we can introduce a new core type for that.

I think we should pull at this thread a bit. I can easily imagine web services accepting a series of top-level Ion values whose length is unknown, similar to [grpc client streaming](https://www.baeldung.com/java-grpc-streaming#basics-of-grpc-streaming). It would be nice for the service to be able to verify that each top-level value adheres to one of a schema's types.

> We can never prove that an unbounded value stream is valid because there is always (in theory) more values that could arrive.

I think this starts to get at the real question here: given a series of top-level Ion values, how do we know that it's a `document` and not an unbounded stream that's still growing?

Intuitively it does seem like there's room for two distinct `document` and `stream` types, but given that Ion doesn't specify a way to terminate a stream it would fall on ISL to provide that functionality. As a straw man, I could imagine requiring the `document` type to specify how many top level values it had, a terminating sentinel value to look for, etc.

**Comment by popematt** [comment]
I've realized that I am operating with some incorrect terminology here, and that's making it confusing. I was using unbounded and infinite/non-terminating interchangeably, which is not right. I'm going to start over, and define the terms so that we can make sure we're on the same page. (Feel free to correct my terminology here if you think these definitions need improvement in order for us to understand each other.)

* If a stream is _bounded_ that means there is a maximum possible/allowed length of the stream, and the stream must terminate before or at that maximum.
* A stream that is _unbounded_ does not have a limit on its length. The actual length of the stream may be a finite even if the stream is unbounded, but it could also be a non-terminating stream.
* A stream that is _non-terminating_ always has another value to offer (though there may be blocking IO required to get). Informally speaking, the length of such a stream is infinite.

My understanding is that an Ion value stream is unbounded _and_ it could be non-terminating. The non-terminating aspect is what I am trying to avoid for `document`. If we allow a document to have an infinite length, then the question of its validity is potentially unanswerable.

What if I were to rephrase things to say that a `document` is unbounded, but it must terminate? Do you still have the same concerns?

**Comment by popematt** [comment]
I'm cancelling my PR since it does not seem like it will actually add any value.

**Pull request closed without merging**
